# Generated by Django 6.0.7 on 2026-08-15 08:12

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_branch_options_alter_branch_table_capacity'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unit', models.CharField(choices=[('bao', 'Bao'), ('chai', 'Chai'), ('thung', 'Thùng'), ('kg', 'Kg'), ('lit', 'Lít'), ('goi', 'Gói')], max_length=20)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='stockrequest',
            name='is_active',
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='stock_item',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='inventory.stockitem'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('branch', 'stock_item')},
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='unit_price',
        ),
    ]
